[versions]
agp = "8.11.1"
kotlin = "2.2.10"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.34.0"
startup = "1.2.0"
equinox = "1.1.6"
kotlin-browser = "0.3.1"
keyring = "1.0.4"
json = "1.9.0"

[libraries]
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }
keyring = { module = "com.github.javakeyring:java-keyring", version.ref = "keyring" }
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }