[versions]
agp = "9.0.0"
kotlin = "2.3.0"
android-compileSdk = "36"
android-minSdk = "24"
mavenPublish = "0.36.0"
dokka = "2.1.0"
startup = "1.2.0"
equinox = "1.1.9beta-01"
kotlin-browser = "0.5.0"
keyring = "1.0.4"
json = "1.10.0"
kotlinx-coroutines = "1.10.2"
windpapi4j = "2.2.0"

[libraries]
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }
keyring = { module = "com.github.javakeyring:java-keyring", version.ref = "keyring" }
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
windpapi4j = { module = "com.github.peter-gergely-horvath:windpapi4j", version.ref = "windpapi4j" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }